language: node_js
node_js: '8'
stages:
  - linting
  - unit-testing
  - coverage
  - name: documentation
    if: branch = master
before_script:
  - npm install -g gulp-cli
jobs:
  include:
    - stage: linting
      script: "gulp linting"
    - stage: unit-testing
      script: "gulp unit-testing"
    - stage: coverage
      script: "npm run coverage && npm run send_coverage"
    - stage: documentation
      script: "gulp documentation"
